# Top-level configuration
# Default config from https://developers.cloudflare.com/workers/wrangler/configuration/
# Stripped down to minimum
name = "crowdclix-frontend"
main = "./src/index.js"
compatibility_date = "2024-01-20"
account_id = "2dccbe1896bc719c10e6502be7070494"