name: Build and Check for Errors

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Check for Errors
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build and Check for Errors
        run: |
          npm install
          npm run build